name: fifa_stats
description: A new Flutter project. Created by Slidy

publish_to: 'none' 

version: 1.0.0+1
 
scripts:
  build: flutter pub run build_runner build
  clear: flutter pub run build_runner clean
  build_delete: flutter pub run build_runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: 
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: 
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#   assets:
#     - lib/app/assets/images/cryptos/coinBase.png

# fonts:
#     - family: Poppins
#       fonts:
#         - asset: lib/assets/fonts/Poppins-ExtraLight.ttf
#           weight: 100
#         - asset: lib/assets/fonts/Poppins-Thin.ttf
#           weight: 200
#         - asset: lib/assets/fonts/Poppins-Light.ttf
#           weight: 300          
#         - asset: lib/assets/fonts/Poppins-Regular.ttf          
#           weight: 400
#         - asset: lib/assets/fonts/Poppins-Medium.ttf          
#           weight: 500
#         - asset: lib/assets/fonts/Poppins-SemiBold.ttf          
#           weight: 600
#         - asset: lib/assets/fonts/Poppins-Bold.ttf
#           weight: 700
#         - asset: lib/assets/fonts/Poppins-Black.ttf
#           weight: 800
#         - asset: lib/assets/fonts/Poppins-ExtraBold.ttf
#           weight: 900 
#         - asset: lib/assets/fonts/Poppins-BoldItalic.ttf
#           style: italic       
